--Acciones

ALTER TABLE Registra
    DROP CONSTRAINT FK_Registra_Estudiante;

ALTER TABLE Registra
    DROP CONSTRAINT FK_Registra_Grupo;

ALTER TABLE Grupo
    DROP CONSTRAINT FK_Grupo_Materia;
    
ALTER TABLE Grupo
    DROP CONSTRAINT FK_Grupo_Extra;

ALTER TABLE Grupo
    DROP CONSTRAINT FK_Grupo_Profesor;

ALTER TABLE SeDictaEn
    DROP CONSTRAINT FK_SeDictaEn_Grupo;

ALTER TABLE SeOcupaPor
    DROP CONSTRAINT FK_SeOcupaPor_Horario;
    
ALTER TABLE Tiene
    DROP CONSTRAINT FK_Tiene_Grupo;
    
ALTER TABLE Decanatura
    DROP CONSTRAINT FK_decano_decanatura;

ALTER TABLE Registra
ADD CONSTRAINT FK_Registra_Estudiante
FOREIGN KEY (idEstudiante) REFERENCES ESTUDIANTE(carne)
ON DELETE CASCADE;

ALTER TABLE Registra
ADD CONSTRAINT FK_Registra_Grupo
FOREIGN KEY (idGrupo) REFERENCES GRUPO(id)
ON DELETE CASCADE;

ALTER TABLE Grupo
ADD CONSTRAINT FK_Grupo_Materia
FOREIGN KEY (siglasMateria) REFERENCES MATERIA(siglas)
ON DELETE CASCADE;

ALTER TABLE Grupo
ADD CONSTRAINT FK_Grupo_Extra
FOREIGN KEY (siglasExtra) REFERENCES CURSOEXTRACURRICULAR(siglase)
ON DELETE CASCADE;

ALTER TABLE Grupo
ADD CONSTRAINT FK_Grupo_Profesor
FOREIGN KEY (idProfe) REFERENCES PROFESOR(noDoc)
ON DELETE SET NULL;

ALTER TABLE SeDictaEn
ADD CONSTRAINT FK_SeDictaEn_Grupo
FOREIGN KEY (idGrupo) REFERENCES GRUPO(id)
ON DELETE CASCADE;

ALTER TABLE SeOcupaPor
ADD CONSTRAINT FK_SeOcupaPor_Horario
FOREIGN KEY (idHorario) REFERENCES HORARIO(id)
ON DELETE CASCADE;

ALTER TABLE Tiene
ADD CONSTRAINT FK_Tiene_Grupo
FOREIGN KEY (idGrupo) REFERENCES Grupo(id)
ON DELETE CASCADE;

ALTER TABLE Decanatura
ADD CONSTRAINT FK_decano_decanatura
FOREIGN KEY (iddecano) REFERENCES Profesor (noDoc)
ON DELETE SET NULL;