--Primarias

ALTER TABLE CURSOEXTRACURRICULAR
ADD CONSTRAINT PK_CursoExtra
PRIMARY KEY (id);

ALTER TABLE DECANATURA
ADD CONSTRAINT PK_Decanatura
PRIMARY KEY (id);

ALTER TABLE ESTUDIANTE 
ADD CONSTRAINT PK_Estudiante
PRIMARY KEY (carne);

ALTER TABLE GRUPO
ADD CONSTRAINT PK_Grupo
PRIMARY KEY (id);

ALTER TABLE HORARIO
ADD CONSTRAINT PK_Horario
PRIMARY KEY (id);

ALTER TABLE MATERIA
ADD CONSTRAINT PK_Materia
PRIMARY KEY (id);

ALTER TABLE PROFESOR
ADD CONSTRAINT PK_Profesor
PRIMARY KEY (noDoc);

ALTER TABLE TIENE
ADD CONSTRAINT PK_Tiene
PRIMARY KEY (idHorario, idGrupo);

ALTER TABLE REGISTRA
ADD CONSTRAINT PK_Registra
PRIMARY KEY (idestudiante, idgrupo);

ALTER TABLE SALON
ADD CONSTRAINT PK_Salon
PRIMARY KEY (id);

ALTER TABLE SEDICTAEN
ADD CONSTRAINT PK_SedictaEn
PRIMARY KEY (idsalon, idgrupo);

ALTER TABLE SEOCUPAPOR
ADD CONSTRAINT PK_SeOcupaPor
PRIMARY KEY (idsalon, idhorario);

