/*
			Foraneas
*/
ALTER TABLE ESTUDIANTE
ADD CONSTRAINT FK_Estudiante_Decanatura1
FOREIGN KEY (Decanatura1) REFERENCES DECANATURA(id);

ALTER TABLE ESTUDIANTE
ADD CONSTRAINT FK_Estudiante_Decanatura
FOREIGN KEY (Decanatura2) REFERENCES DECANATURA(id);

ALTER TABLE REGISTRA
ADD CONSTRAINT FK_Registra_Estudiante
FOREIGN KEY (idEstudiante) REFERENCES ESTUDIANTE(carne)
ON DELETE CASCADE;

ALTER TABLE REGISTRA
ADD CONSTRAINT FK_Registra_Grupo
FOREIGN KEY (idGrupo) REFERENCES GRUPO(id)
ON DELETE CASCADE;

ALTER TABLE GRUPO
ADD CONSTRAINT FK_Grupo_Materia
FOREIGN KEY (siglasMateria) REFERENCES MATERIA(siglas)
ON DELETE CASCADE;

ALTER TABLE GRUPO
ADD CONSTRAINT FK_Grupo_Extra
FOREIGN KEY (siglasExtra) REFERENCES CURSOEXTRACURRICULAR(siglase)
ON DELETE CASCADE;

ALTER TABLE GRUPO
ADD CONSTRAINT FK_Grupo_Profesor
FOREIGN KEY (idProfe) REFERENCES PROFESOR(noDoc)
ON DELETE CASCADE;

ALTER TABLE MATERIA
ADD CONSTRAINT FK_Materia_Decanatura
FOREIGN KEY (idDecanatura) REFERENCES DECANATURA(id);

ALTER TABLE SEDICTAEN
ADD CONSTRAINT FK_SeDictaEn_Salon
FOREIGN KEY (idSalon) REFERENCES SALON(id);

ALTER TABLE SEDICTAEN
ADD CONSTRAINT FK_SeDictaEn_Grupo
FOREIGN KEY (idGrupo) REFERENCES GRUPO(id)
ON DELETE CASCADE;

ALTER TABLE SEOCUPAPOR
ADD CONSTRAINT FK_SeOcupaPor_Salon
FOREIGN KEY (idSalon) REFERENCES SALON(id);

ALTER TABLE SEOCUPAPOR
ADD CONSTRAINT FK_SeOcupaPor_Horario
FOREIGN KEY (idHorario) REFERENCES HORARIO(id)
ON DELETE CASCADE;

ALTER TABLE Tiene
ADD CONSTRAINT FK_Tiene_Horario
FOREIGN KEY (idHorario) REFERENCES Horario(id);

ALTER TABLE Tiene
ADD CONSTRAINT FK_Tiene_Grupo
FOREIGN KEY (idGrupo) REFERENCES Grupo(id);